### ISSUE TITLE
Create bricks based on original blocks

### ISSUE THREAD

**Issue by alexcarol** [adobe-gw2023-project-bricks/helix-website-wc#2]
Create webcomponents based on the original [helix-website/blocks](https://github.com/adobe/helix-website/tree/main/blocks):
To start working on them just hover over the element, and click "create issue" on the right (the circle with a dot inside), then just assign it to yourself. Make sure to find a usage of the block in the google drive before you start working on it to ensure that the block is actually in use.
Reference:
![image](https://github.com/adobe-gw2023-project-bricks/helix-website-wc/assets/1713440/b350af33-1018-40ee-ae16-aa31c7511b78)

- [ ] accordion brick
- [ ] card-list brick
- [ ] cards brick
- [x] #14
- [ ] copy brick
- [ ] embed brick
- [ ] faq brick
- [ ] feature-list brick
- [ ] footer brick
- [ ] footnotes brick
- [ ] form brick
- [ ] fragment brick
- [ ] get-started brick
- [ ] #24 
- [x] #10
- [ ] labs brick
- [x] #12
- [ ] marquee brick
- [ ] pagination brick
- [ ] releases brick
- [x] #16
- [ ] service-status brick
- [ ] side-navigation brick
- [ ] sidekick-generator brick
- [ ] sidekick-library brick
- [ ] svg-doctor brick
- [ ] table brick
- [ ] tabs brick
- [x] #15
- [ ] #19 
- [ ] videotext brick
- [x] #13

**Comment by dicagno** [comment]
@alexcarol @hannessolo @lansami since here we mention "bricks" maybe would be good to rename references from "blocks" to "bricks"? This for "branding" of the Garage Week Project, as well as to distinguish from the original "blocks". Wdyt?

**Comment by fnhipster** [comment]
I don't want to start philosophical conversations BUT what's a Block? Is it the codebase or does the definition of a Block begins with the author creating the "block" table? I want to make sure we are not presenting the idea of moving from one to the other.
